title: "VEXcode Tutorials"
description: "Learning hub for VEX robotics programming."
theme: just-the-docs
url: "https://hakopz.github.io/vexcode-programming"

# Optional search
just_the_docs:
  search_enabled: true
